Completed CRUD
LeonardM01/SyncMeet pull request #74
Opened 2024-05-13 15:31 UTC by mateod062

Complete CRUD operations for all basic entities: ```user```, ```event```, ```blog```, ```comment```. Implemented request sending for events and friendship. Created Javadocs for most methods and classes.

2024-05-15 17:39 UTC, TinUgle2002 commented on backend/src/main/java/com/example/syncmeet/controller/CommentController.java
> +
Poziv na ovaj endpoint napravi dupli komentar u databazi. U JSON-u se dobro pokaže koji su replying komentari, ali u DB se ne puni `replying_comment_id`.

2024-05-15 17:43 UTC, TinUgle2002 commented on backend/src/main/java/com/example/syncmeet/controller/CommentController.java
> +
Reply komentari se ne briši iz DB pozivom na **deleteComment()**.

2024-05-15 17:46 UTC, TinUgle2002 requested changes

2024-05-15 17:46 UTC, TinUgle2002 commented on backend/src/main/java/com/example/syncmeet/controller/CommentController.java
> +
Poziv na ovaj endpoint napravi dupli komentar u databazi. U JSON-u se dobro pokaže koji su replying komentari.

2024-05-15 17:46 UTC, TinUgle2002 commented on backend/src/main/java/com/example/syncmeet/controller/CommentController.java
> +    }
Reply komentari se ne brišu iz DB pozivom na `deleteComment()`.

2024-05-15 18:25 UTC, mateod062 commented on backend/src/main/java/com/example/syncmeet/controller/CommentController.java
> +    }
Misliš na komentare iz replyingComment varijable ili opcenito kada komentar replya na drugi da se ne izbriše?

2024-05-20 11:05 UTC, TinUgle2002 approved these changes

2024-05-20 11:05 UTC, merged